CREATE DATABASE IF NOT EXISTS UyBNjCScGvg;
CREATE TABLE UyBNjCScGvg.HcLozrCIbNI LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.HcLozrCIbNI SELECT * FROM hortoniabank.us_customers LIMIT 24534;
CREATE TABLE UyBNjCScGvg.PDSbVmZPHHw LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.PDSbVmZPHHw SELECT * FROM hortoniabank.us_customers LIMIT 8322;
CREATE TABLE UyBNjCScGvg.PHguPwlhpxo LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.PHguPwlhpxo SELECT * FROM hortoniabank.us_customers LIMIT 25279;
CREATE TABLE UyBNjCScGvg.QppsaRcTiSr LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.QppsaRcTiSr SELECT * FROM hortoniabank.us_customers LIMIT 39677;
CREATE TABLE UyBNjCScGvg.UGvkLkLTPFj LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.UGvkLkLTPFj SELECT * FROM hortoniabank.us_customers LIMIT 38791;
CREATE TABLE UyBNjCScGvg.RcwPWdxoEJp LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.RcwPWdxoEJp SELECT * FROM hortoniabank.us_customers LIMIT 40936;
CREATE TABLE UyBNjCScGvg.PChtbZUDUcC LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.PChtbZUDUcC SELECT * FROM hortoniabank.us_customers LIMIT 6770;
CREATE TABLE UyBNjCScGvg.WWotqPXQdir LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.WWotqPXQdir SELECT * FROM hortoniabank.us_customers LIMIT 3261;
CREATE TABLE UyBNjCScGvg.FkIItrBWTvK LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.FkIItrBWTvK SELECT * FROM hortoniabank.us_customers LIMIT 45426;
CREATE TABLE UyBNjCScGvg.ZBMFNjLfaNQ LIKE hortoniabank.us_customers;
INSERT INTO UyBNjCScGvg.ZBMFNjLfaNQ SELECT * FROM hortoniabank.us_customers LIMIT 8511;

CREATE DATABASE IF NOT EXISTS PsMPRredNsw;
CREATE TABLE PsMPRredNsw.MyUBEKlyjWV LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.MyUBEKlyjWV SELECT * FROM hortoniabank.us_customers LIMIT 39090;
CREATE TABLE PsMPRredNsw.FtCdFUGPnEi LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.FtCdFUGPnEi SELECT * FROM hortoniabank.us_customers LIMIT 30123;
CREATE TABLE PsMPRredNsw.UiuNPiXmaHI LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.UiuNPiXmaHI SELECT * FROM hortoniabank.us_customers LIMIT 42889;
CREATE TABLE PsMPRredNsw.RfiAUTyxrwL LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.RfiAUTyxrwL SELECT * FROM hortoniabank.us_customers LIMIT 14034;
CREATE TABLE PsMPRredNsw.EmEANvoMFrw LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.EmEANvoMFrw SELECT * FROM hortoniabank.us_customers LIMIT 29211;
CREATE TABLE PsMPRredNsw.XQUzaYkRiGf LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.XQUzaYkRiGf SELECT * FROM hortoniabank.us_customers LIMIT 12044;
CREATE TABLE PsMPRredNsw.SzBxkfQvYpX LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.SzBxkfQvYpX SELECT * FROM hortoniabank.us_customers LIMIT 30561;
CREATE TABLE PsMPRredNsw.WcmXdadrxjg LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.WcmXdadrxjg SELECT * FROM hortoniabank.us_customers LIMIT 39719;
CREATE TABLE PsMPRredNsw.DIUeGZUFUpJ LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.DIUeGZUFUpJ SELECT * FROM hortoniabank.us_customers LIMIT 7244;
CREATE TABLE PsMPRredNsw.DNSNJevcfuR LIKE hortoniabank.us_customers;
INSERT INTO PsMPRredNsw.DNSNJevcfuR SELECT * FROM hortoniabank.us_customers LIMIT 20398;

