---
swagger: '2.0'
info:
  title: DSS Canned Collection APIs
  version: 0.0.1
  description: |
    Proposed API for canned collections to be used by DSS UI to compute canned collection metadata and fetch results for queries
consumes:
  - application/json
produces:
  - application/json

paths:
  /canned-query:
    post:
      summary: Execute a canned collection query
      parameters:
        - in: body
          name: canned_query
          required: true
          schema:
            $ref: '#/definitions/CannedCollectionQuery'
      responses:
        202:
          description: Response indicating that the query request was accepted and the query results will be available in the response
          schema:
            description: Results of the Query executed by Livy Interactive Session
            type: object
            properties:
              data:
                description: Query results in the JSON format
                type: array
                items:
                  $ref: '#/definitions/Data'
        400:
          description: Malformed request
          schema:
            $ref: '#/definitions/Error'
            
        503:
          description: Livy Interactive is not running 
          schema:
            $ref: '#/definitions/Error'
            
        500:
          description : Internal server error
          schema:
            $ref: '#/definitions/Error'
            
            
            
  /canned-collection:
    post:
      summary: Request to compute the canned collection dataframe from the metadata of Hive tables on the cluster
      parameters:
        - in: body
          name: canned_collection_computation_request
          required: true
          schema:
            $ref: '#/definitions/Path'
            
      responses:
        202:
          description: Response with YARN job ID so that the Spark job execution can be tracked
          schema:
            $ref: '#/definitions/Job'
                  
        400:
          description: Malformed request
          schema:
            $ref: '#/definitions/Error'

        500:
          description : Internal server error
          schema:
            $ref: '#/definitions/Error'
            
  


definitions:
  CannedCollectionQuery:
    type: object
    required :
      - sql
      - path
      
    properties:
      sql:
        type: string
        description : SQL query to run on the Hive metadata dataframe. Example - 'select table, size from cannedCollectionTable order by size desc limit 10'
          
      path:
        type: string
        description: Path where the metadata dataframe is stored on HDFS
      
  Path:
    type: object
    required:
      - path
    properties:
      path:
        type: string
        description: Path where the metadata dataframe is stored on HDFS
        
  Job:
    type: object
    required:
      - job_id
      - start_time
    properties:
      job_id:
        type: string
        description: Unique Job ID assigned by YARN to the Spark job for canned collection computation
        
      start_time:
        type: string
        description: Timestamp when this job was started on cluster
  
  Data:
    type: object
      
  Error:
    type: object
    required:
      - code
      - description
    properties:
      code:
        type: string
        description: Error code
      description:
        type: string
        description: A generic description for the error code
